name: Ad hoc ingest java 8

on:
  workflow_dispatch:
    inputs:
      repositoryToIngest:
        description: "Github organization/repository"
        required: true
      styleName:
        description: "Style name"
        required: false

jobs:
  ingest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - name: Checkout repository to ingest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repositoryToIngest }}
      - name: ingest with style
        if: ${{ github.event.inputs.styleName != null }}
        uses: docker://moderne/ingest:java8-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
        with:
          args: --style-name ${{ github.event.inputs.styleName }}
      - name: ingest without style
        if: ${{ github.event.inputs.styleName == null }}
        uses: docker://moderne/ingest:java8-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
