name: Bigkoo/Android-PickerView ingest

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - 'EMERGENCY-INGEST-0.md'
  workflow_dispatch: {}

jobs:
  ingest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Bigkoo/Android-PickerView
      - name: Ingest
        uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN:     ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
      - name: Slack Notify on Failure
        if:     ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK:     ${{ secrets.SLACK_ALERTS_WEBHOOK }}
          SLACK_USERNAME: moderne-ingest
          SLACK_COLOR: red
          SLACK_ICON: https://image.pngaaa.com/813/2886813-middle.png
          SLACK_TITLE: Ingest workflow failure
          SLACK_MESSAGE: We all have bad days