name: eclipse/kapua ingest

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - 'EMERGENCY-INGEST-1.md'
  workflow_dispatch: {}

jobs:
  ingest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: eclipse/kapua
      - name: Ingest
        uses: docker://moderne/ingest:java8-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
