name: ltsopensource/light-task-scheduler ingest

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - 'EMERGENCY-INGEST-2.md'
  workflow_dispatch: {}

jobs:
  ingest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ltsopensource/light-task-scheduler
      - name: Ingest
        uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN:     ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
