name: spring-cloud/spring-cloud-gateway ingest

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - 'EMERGENCY-INGEST-3.md'
  workflow_dispatch: {}

jobs:
  ingest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ingest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: spring-cloud/spring-cloud-gateway
      - name: Ingest
        uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN:     ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
        with:
          args: --style-name org.openrewrite.java.SpringFormat
